spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: root
    password: auto3010
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never